### ISSUE TITLE
'gulp' command replaced index.html

### ISSUE THREAD

**Issue by patricklittle** [40Digits/gulp-eta#17]
tested in 2 separate clean installs of the gulp-eta. when you run the gulp command index.html will be replaced with the default markup every time.

**Comment by smacpherson64** [comment]
Hey Patrick,

I believe this happens because `gulp` runs the static html task which generates static html files from the `_src/static/` folder. The default one in that folder is `index.tpl.html`. This one will overwrite the default index.html at the base of default config.

**Comment by prichey** [comment]
Yup, @smacpherson64 is right, the default task runs `static` (see here: https://github.com/40Digits/gulp-eta/blob/master/lib/config.js#L191). Maybe there's an argument to be made that it _shouldn't_ do that, but at least as it's written now that's the expected behavior. 

Running `gulp` alone regenerates several things that don't need to be regenerated after the start of the project. `gulp watch` should be your go-to most of the time.

**Comment by hahnzilla** [comment]
+1 for taking the static task out of the default tasks. Since you have to manually add a gulpfile.js anyways, maybe we should make all the tasks opt-in. Meaning, we take line 191 and make it an empty array and in the example gulpfile.js we add that config line.

The only reason I suggest that is because it seems like that default config seems to get in the way quite a bit.

**Comment by prichey** [comment]
My vote is to remove the static task from the default tasks. I don't mind the idea of having the default task be custom, though it seems like the static issue is the only real confusion people have had, so it seems to me like just taking it out would be an okay solution for now?

**Comment by chadwatson** [comment]
Resolved [in this pull request](https://github.com/40Digits/gulp-eta/pull/20)
